### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by tamerNasser** [facn5/BloodDonor#4]
- [x] Open user stories related to the first milestone.
- [x] Add dwyl labels. @tamerNasser  
- [x] Setup linting rules. @tamerNasser 
- [x] Setup Travis CI. - @obayda 
- [x] Architecture design. @majdya 
- [x] Decide on the tech-stack. 
- [ ] Set up initial App 
- [x] Host on Heroku for CD. @karam1ashqar 
- [x] research MongoDB @majdya 
- [ ] research Jest @karam1ashqar

**Comment by karam1ashqar** [comment]
Jest research resources:
[Jest official webite](https://jestjs.io/docs/en/tutorial-react)

**Comment by tawfiknasser** [comment]
#11
